name: Test Binaries

on: repository_dispatch

jobs:
  test-binaries:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Show environment
      run: |
        env
        ls -l
        ls -l scripts
        ls -l .github/workflows
    - name: Run the test script
      run: bash .github/workflows/action-test-binaries.sh
    
