name: Test Binaries

on: repository_dispatch

jobs:
  test-binaries:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Show environment
      run: |
        env
        pwd
        ls -l
    - name: Run a one-line script
      run: echo Testing...
    
